[package]
name = "types_var_ex"
version = "0.1.0"
authors = ["bradleypmartin <brad.martin@ibotta.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
