[package]
name = "hello_world"
version = "0.1.0"
authors = ["Brad Martin <brma7253@colorado.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
